# Site settings
title: Harmony & Eric
email: eric.harmony@rudz.fr
url: https://20220514.github.io
description: "14 Mai 2022"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-light: '#dfb0b0'
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Eric RUDZ

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

# Build settings
markdown: kramdown
permalink: pretty
