# Site settings
title: Harmonie & Eric
email: eric.harmony@rudz.fr
url: https://20220514.github.io
description: "14 Mai 2022"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-light: '#F5CEF3'
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Harmonie et Eric

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

# Build settings
markdown: kramdown
permalink: pretty

include:
  - _map
